// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXILAlHD7g28JAZyQK7BPoK4V1dYFrQjM',
    appId: '1:704859787547:android:d758e244ef111d9a0403be',
    messagingSenderId: '704859787547',
    projectId: 'envycar-57c04',
    storageBucket: 'envycar-57c04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwpAJoNIAHMYo9Q7FLNgNgR19WJSgIzCg',
    appId: '1:704859787547:ios:f5ccd5b097c5f5a70403be',
    messagingSenderId: '704859787547',
    projectId: 'envycar-57c04',
    storageBucket: 'envycar-57c04.appspot.com',
    androidClientId: '704859787547-rl5t6gg6hltte9684gaq3d8qmvcn4fms.apps.googleusercontent.com',
    iosClientId: '704859787547-6kaifl1lkjt9m6nsf1m5no89k634ncl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.envyCar',
  );
}
